import type { Metadata } from "next";
import { Mitr, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import "@/app/_lib/Page/Home/react-view360.css";


const mitr = Mitr({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-mitr"
});

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mitr.className} ${jakartaSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
